/*
 * @LastEditors: aFei
 * @LastEditTime: 2022-12-06 09:51:57
*/
(function(n){typeof define=="function"&&define.amd?define(n):n()})(function(){"use strict";let n=[],d,o,h,u=1,C=42,i=[],p=["\u65E5","\u4E00","\u4E8C","\u4E09","\u56DB","\u4E94","\u516D"];function w(){let e=new Date;d=e.getFullYear(),o=e.getMonth()+1,h=e.getDate(),e.getDay(),$(".date_selector .body").attr("class","body day"),_(),c(d,o)}function _(){let e=[],t=u;for(let r=0;r<7;r++,t++)t>6&&(t=0),e.push(p[t]);let a=[...e],l="";for(let r=0;r<a.length;r++)r===0&&(l+='<div class="row">'),l+=`<div class="item"><div class="inner">${a[r]}</div></div>`,r===a.length-1&&(l+="</div>");$(".date_selector .title").html(l)}function D(e){return e%4===0?e%100===0?e%400===0:!0:!1}function v(e,t){t===0?(e=e-1,t=12):t===13&&(e=e+1,t=1);let a=D(e);switch(t){case 1:return 31;case 2:return a?29:28;case 3:return 31;case 4:return 30;case 5:return 31;case 6:return 30;case 7:return 31;case 8:return 31;case 9:return 30;case 10:return 31;case 11:return 30;case 12:return 31}}function c(e,t){let a=new Date,l,r,g,m;i=[],m=v(e,t);for(let s=1;s<=m;s++)i.push({num:s,data:`${e}-${t}-${s}`,today:e===d&&t===o&&s===h,afterDay:e>d||e===d&&t>o||e===d&&t===o&&s>h});a.setFullYear(e),a.setMonth(t-1),a.setDate(1),l=a.getDay(),l-u>0?r=l-u:r=7+(l-u);let b=v(e,t-1);for(let s=0;s<r;s++)i.unshift({num:b-s,cantUse:!0,data:`${t-1<1?e-1:e}-${t-1<1?12:t-1}-${b-s}`});g=C-i.length;for(let s=1;s<=g;s++)i.push({num:s,cantUse:!0,data:`${t+1>12?e+1:e}-${t+1>12?1:t+1}-${s}`});let f="";for(let s=0;s<i.length;s++)s===0&&(f+='<div class="row">'),f+=`<div class="item ${i[s].cantUse===!0?"cantUse":""}
            ${i[s].afterDay===!0?"noHover":""}
            ${i[s].today===!0?"today":""}"
            data-time="${i[s].data}">
                <div class="inner">
                    ${i[s].num}      
                </div>
            </div>`,(s+1)%7===0&&(s!==i.length-1?f+='</div><div class="row">':f+="</div>");$(".date_selector .head .year div").html(e),$(".date_selector .head .month div").html(t),$(".date_selector .body").html(f)}$("body").on("click",".date_selector .head .year .btn",function(e){let t=parseInt($(e.target).parent().find("div").html()),a=parseInt($(".date_selector  .head .month div").html());$(e.target).hasClass("prev")?c(t-1,a):c(t+1,a)}).on("click",".date_selector .head .month .btn",function(e){let t=parseInt($(".date_selector  .head .year div").html()),a=parseInt($(e.target).parent().find("div").html());$(e.target).hasClass("prev")?(a-1<1?(t-=1,a=12):a-=1,c(t,a)):(a+1>12?(t+=1,a=1):a+=1,c(t,a))}).on("click",".date_selector .body .item",function(){if(!$(this).closest(".body").hasClass("doubleDay"))if($(this).closest(".body").hasClass("week")){$(".date_selector .body .item").removeClass("select between");let e=$(this).closest(".row").find(".item"),t,a;for(let l=0;l<e.length;l++)l===0?t=$(e[l]).addClass("select").attr("data-time"):l===e.length-1&&(a=$(e[l]).addClass("select").attr("data-time")),$(e[l]).addClass("between");n[0]=t,n[1]=a,$("#a").val(t+" \u5230 "+a)}else $(".date_selector .body .row").removeClass("select"),!$(this).hasClass("cantUse")&&!$(this).hasClass("noHover")&&($(".date_selector .body .item").removeClass("select"),$(this).addClass("select"),$("#a").val($(this).attr("data-time")),n[0]=$(this).attr("data-time"))}),window.init=w});