/*
 * @LastEditors: aFei
 * @LastEditTime: 2022-12-06 10:19:44
*/
(function(e){typeof define=="function"&&define.amd?define(e):e()})(function(){"use strict";$(".section .xpst").on("click",function(){window.open("index.html")}),$(".section .yxcg").on("click",function(){window.open("index.html")}),$(".section .kctx .gear").on("click",function(){$(".top").addClass($(this).attr("class").replace("gear","").trim()),$(this).addClass("active")}),$(".top .close-img").on("click",function(){$(this).closest("div").attr("class","top"),$(".section .kctx .gear.active").removeClass("active")}),$(document).ready(function(){$.ajax({type:"GET",url:"data/home.json",dataType:"json",success:function(e){$(".section .xpst .school em").text(e.xpst.school),$(".section .xpst .enterprise em").text(e.xpst.enterprise),$(".section .xpst .student em").text(e.xpst.student);let l=echarts.init($(".section .yxgk .chart")[0]),a={color:["#1269c5","#9091ff","#c16bf1","#5146b7","#00adc3"],tooltip:{trigger:"item",formatter:"{a} <br/>{b}: {c} ({d}%)"},textStyle:{fontSize:15},series:[{name:e.yxgk.inData.name,type:"pie",selectedMode:"single",radius:[0,"30%"],label:{normal:{position:"inner"}},labelLine:{normal:{show:!1}},data:e.yxgk.inData.data},{name:e.yxgk.outData.name,type:"pie",radius:["48%","58%"],data:e.yxgk.outData.data}]};l.setOption(a),e.cptx.dsj.forEach(function(t){$(".section .cptx .dsj").append(`<span>${t}</span>`)}),e.cptx.rgzn.forEach(function(t){$(".section .cptx .rgzn").append(`<span>${t}</span>`)}),e.cptx.wlaq.forEach(function(t){$(".section .cptx .wlaq").append(`<span>${t}</span>`)});let r=echarts.init($("#map")[0]),p={backgroundColor:"transparent",tooltip:{trigger:"item",enterable:!0,backgroundColor:"transparent",position:function(t){return event.pageX+346>$(window).width()&&(t[0]=event.offsetX-346),event.pageY+271>$(window).height()&&(t[1]=event.offsetY-271),t},formatter:function(t,o,n){let i="";t.data!==void 0&&t.data.logo!==void 0&&t.data.logo.forEach(function(c){i+=`<img src="img/college-logo/${c}">`});let s=`
        <div class="mapTip">
            <p>${t.name}\u670D\u52A1\u9662\u6821--${t.value}</p>
            <div class="list">${i}</div>
        </div>`;return t.name!==""?s:""}},visualMap:{show:!1,x:"left",y:"bottom",splitList:[{start:40,end:600},{start:25,end:40},{start:15,end:25},{start:5,end:15},{start:0,end:5},{start:0,end:0}],color:["#215096","#3598c1","#40a9ed","#b7d6f3","#edfbfb"]},series:[{name:"\u5168\u56FD\u6570\u636E",type:"map",mapType:"china",roam:!0,itemStyle:{normal:{borderColor:"#25a2d3"}},label:{normal:{show:!0},emphasis:{show:!0}},data:e.map}]};r.setOption(p),$(".section .yxcg .content").append('<div class="group"></div>');let d=Math.ceil(e.yxcg.length/3);for(let t=0;t<d;t++){let o="";for(let n=0;n<3;n++)o+=e.yxcg[3*t+n]===void 0?"":`<div class="item">
                    <div class="logo">
                    <img src="img/college-logo/${e.yxcg[3*t+n].logo}">
                    </div>
                    <p>${e.yxcg[3*t+n].name}</p>
                   </div>`;$(".section .yxcg .group").append(`<div class="row">${o}</div>`)}if(e.yxcg.length>3){let t=$(".section .yxcg .content"),o=t.html();t.html(o+o);let n=t.children(".group:first-child").css("top",0).height(),i=50;t.children(".group:last-child").css("top",n+12);let s=0,c=function(){s%2===0?(t.children(".group:first-child").animate({top:-n-12},n/i*1e3,function(){$(this).css("top",n+12)}),t.children(".group:last-child").animate({top:0},n/i*1e3)):(t.children(".group:last-child").animate({top:-n-12},n/i*1e3,function(){$(this).css("top",n+12)}),t.children(".group:first-child").animate({top:0},n/i*1e3)),s=s+1>1?0:s+1};setInterval(c,n/i*1e3),c()}}})})});